linters-settings:
  cyclop:
    max-complexity: 20
  funlen:
    lines: 100
linters:
  enable-all: true
  disable:
    - testpackage
    - exhaustruct
    - exhaustivestruct
    - tagliatelle
    - maligned
    - gomnd
    - scopelint
    - interfacer
    - golint
    - gomoddirectives
    - ifshort
    - contextcheck
    - rowserrcheck
    - structcheck
    - sqlclosecheck
    - wastedassign