version: '3.5'

services:
  gopherobot:
    image: ghcr.io/m4tthewde/gopherobot:latest
    container_name: gopherobot
    restart: always
    network_mode: host
    volumes:
      - ./config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
