name: Go

on:
  push:
    branches:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install vips
      run: |
        sudo apt update && sudo apt -y install libvips-dev

    - name: Download Modules
      run: go get

    - name: Build
      run: go build -v

    - name: Test
      run: go test ./... -v
