name: golangci-lint
on:
  push:
    branches:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install vips
        run: |
          sudo apt update && sudo apt -y install libvips-dev

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.48.0
