name: golangci-lint
on:
  push:
    branches:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install vips
        run: |
          sudo add-apt-repository -y ppa:strukturag/libde265
          sudo add-apt-repository -y ppa:strukturag/libheif
          sudo add-apt-repository ppa:tonimelisma/ppa
          sudo apt-get -y install libvips-dev

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.48.0
